name: modo
description: 자신의 글을 올리고 같이 꿈을 이룰 파트너를 찾는 어플리케이션

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  provider : ^4.0.4
  firebase_core: ^0.4.4
  cloud_firestore: ^0.13.0+1
  flutter_slidable: "^0.5.4"
  firebase_storage: ^3.1.5
  sqflite: any
  path_provider: any
  zefyr: any
  firebase_auth: any
  flutter_swiper: any
  image_picker: any
  http: any
  intl: any
  epub: ^2.0.0
  reorderables: any
  pull_to_refresh: ^1.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/room4.jpg
    - assets/books1.jpg
    - assets/appstore.png
    - assets/playstore.png
    - assets/sample.epub
